/**
 * S3 Image URL Construction Utilities
 *
 * This module provides utilities for constructing S3 image URLs from base paths
 * stored in the database. The backend stores base paths (e.g., "uploads/abc-123")
 * and generates multiple image versions (small, medium, large) in WebP format.
 *
 * @module s3-url
 */

/**
 * S3 configuration loaded from environment variables.
 * These must be set in .env files for both RMS and SOS apps.
 */
const AWS_S3_BUCKET = process.env.NEXT_PUBLIC_AWS_S3_BUCKET;
const AWS_REGION = process.env.NEXT_PUBLIC_AWS_REGION;

/**
 * Validates S3 configuration and logs warning in development if missing.
 * Returns true if configuration is valid, false otherwise.
 */
function isS3ConfigValid(): boolean {
  const isValid = !!(AWS_S3_BUCKET && AWS_REGION);

  if (!isValid && process.env.NODE_ENV === 'development') {
    console.warn(
      'S3 configuration missing. Images will not display. Please set NEXT_PUBLIC_AWS_S3_BUCKET and NEXT_PUBLIC_AWS_REGION in your .env file.'
    );
  }

  return isValid;
}

/**
 * Available image size versions generated by the backend
 */
export type ImageSizeVersion = 'small' | 'medium' | 'large';

/**
 * Image size dimensions (width in pixels)
 */
export const IMAGE_SIZES = {
  small: 400,
  medium: 800,
  large: 1200,
} as const;

/**
 * Constructs full S3 URL from base path and size version.
 * Used for menu items and other assets that have multiple size versions.
 *
 * Backend stores: `uploads/abc-123-def`
 * Frontend constructs: `https://bucket.s3.region.amazonaws.com/uploads/abc-123-def-medium.webp`
 *
 * @param basePath - Base S3 path without size suffix or extension (e.g., "uploads/abc-123-def")
 * @param size - Image size version to fetch (default: "medium")
 * @returns Full S3 URL with size suffix and .webp extension, or null if basePath is invalid
 *
 * @example
 * ```typescript
 * getImageUrl("uploads/abc-123", "medium")
 * // Returns: "https://bucket.s3.us-east-1.amazonaws.com/uploads/abc-123-medium.webp"
 *
 * getImageUrl("uploads/abc-123", "small")
 * // Returns: "https://bucket.s3.us-east-1.amazonaws.com/uploads/abc-123-small.webp"
 *
 * getImageUrl(null)
 * // Returns: null
 * ```
 */
export function getImageUrl(
  basePath: string | null | undefined,
  size: ImageSizeVersion = 'medium'
): string | null {
  if (!basePath) return null;

  if (!isS3ConfigValid()) {
    return null;
  }

  const result = `https://${AWS_S3_BUCKET}.s3.${AWS_REGION}.amazonaws.com/${basePath}-${size}.webp`;
  console.log('🚀 ~ getImageUrl ~ result:', result);

  return `https://${AWS_S3_BUCKET}.s3.${AWS_REGION}.amazonaws.com/${basePath}-${size}.webp`;
}

/**
 * Constructs full S3 URL from complete S3 key.
 * Used for store branding assets (logos, cover photos) that are stored as complete S3 keys.
 *
 * Backend stores: `store-logos/store-id-123-logo.png` (full S3 key with extension)
 * Frontend constructs: `https://bucket.s3.region.amazonaws.com/store-logos/store-id-123-logo.png`
 *
 * @param s3Key - Complete S3 key including path and extension (e.g., "store-logos/store-id-logo.png")
 * @returns Full S3 URL, or null if s3Key is invalid
 *
 * @example
 * ```typescript
 * getDirectUrl("store-logos/abc-123.png")
 * // Returns: "https://bucket.s3.us-east-1.amazonaws.com/store-logos/abc-123.png"
 *
 * getDirectUrl("store-covers/abc-123-cover.jpg")
 * // Returns: "https://bucket.s3.us-east-1.amazonaws.com/store-covers/abc-123-cover.jpg"
 *
 * getDirectUrl(null)
 * // Returns: null
 * ```
 */
export function getDirectUrl(s3Key: string | null | undefined): string | null {
  if (!s3Key) return null;

  if (!isS3ConfigValid()) {
    return null;
  }

  return `https://${AWS_S3_BUCKET}.s3.${AWS_REGION}.amazonaws.com/${s3Key}`;
}

/**
 * Generates srcset string for responsive images with multiple size versions.
 * Used with <img> srcSet attribute for responsive image loading.
 *
 * @param basePath - Base S3 path without size suffix or extension
 * @returns srcset string with all available sizes, or null if basePath is invalid
 *
 * @example
 * ```typescript
 * const srcSet = getResponsiveSrcSet("uploads/abc-123");
 * // Returns:
 * // "https://bucket.s3.region.amazonaws.com/uploads/abc-123-small.webp 400w,
 * //  https://bucket.s3.region.amazonaws.com/uploads/abc-123-medium.webp 800w,
 * //  https://bucket.s3.region.amazonaws.com/uploads/abc-123-large.webp 1200w"
 *
 * // Usage in component:
 * <img
 *   src={getImageUrl(basePath, "medium")}
 *   srcSet={getResponsiveSrcSet(basePath)}
 *   sizes="(max-width: 640px) 400px, (max-width: 1024px) 800px, 1200px"
 * />
 * ```
 */
export function getResponsiveSrcSet(
  basePath: string | null | undefined
): string | null {
  if (!basePath) return null;

  const small = getImageUrl(basePath, 'small');
  const medium = getImageUrl(basePath, 'medium');
  const large = getImageUrl(basePath, 'large');

  if (!small || !medium || !large) return null;

  return `${small} ${IMAGE_SIZES.small}w, ${medium} ${IMAGE_SIZES.medium}w, ${large} ${IMAGE_SIZES.large}w`;
}
